# YAML File for SMPy Configuration

#------General settings------#
general:
  # Input/Output paths
  input_path: "/Users/vassig/research/SMPy/examples/data/forecast_lum_truth.fits"
  input_hdu: 1  # FITS extension number to read data from
  output_directory: "/Users/vassig/research/SMPy/examples/outputs/"
  output_base_name: "truth_testing"

  # Coordinate system settings
  coordinate_system: "radec"  # 'radec' or 'pixel'
  radec:
    resolution: 0.4  # In arcminutes
    coord1: 'ra'    # RA column name
    coord2: 'dec'   # Dec column name
  pixel:
    downsample_factor: 170  # Grid reduction factor
    coord1: 'X_IMAGE_se'    # X column name
    coord2: 'Y_IMAGE_se'    # Y column name
  
  # Data columns
  g1_col: 'nfw_g1'
  g2_col: 'nfw_g2'
  weight_col: null  # Set to null if no weights
  
  # Analysis settings
  method: "kaiser_squires"  # "kaiser_squires" or "aperture_mass"
  create_snr: true  # Whether to create SNR map
  mode: ['E']  # ['E'], ['B'], or ['E', 'B']

#------Method Settings------#
methods:
  # Kaiser-Squires settings
  kaiser_squires:
    smoothing:
      type: 'gaussian'  # 'gaussian' or null
      sigma: 2.0        # Smoothing scale

  # Aperture Mass settings
  aperture_mass:
    filter:
      type: 'schirmer'  # Type of aperture filter
      scale: 60        # Filter scale

#------Plot Settings------#
plotting:
  # Basic plotting
  figsize: [20, 10]
  cmap: 'magma'
  xlabel: 'auto'  # 'auto', null, or custom string
  ylabel: 'auto'  # 'auto', null, or custom string
  plot_title: 'Mass Map'  # Method name will be appended
  gridlines: true
  
  # Advanced plotting
  vmax: null
  vmin: null
  threshold: null    # Peak detection threshold
  verbose: null      # Print peak information
  cluster_center: null  # null, 'auto', or {ra/x_center: float, dec/y_center: float}

#------SNR Map Settings------#
snr:
  shuffle_type: 'spatial'  # 'spatial' or 'orientation'
  num_shuffles: 100       # Number of random realizations
  
  smoothing:
    type: 'gaussian'  # 'gaussian' or null (null not recommended for SNR)
    sigma: 2.0        # Smoothing scale
  
  # SNR plots will use the same settings as defined in plotting section above
  plot_title: 'Signal-to-Noise Map'  # Overrides plotting.plot_title for SNR maps