name: Paper Draft

on:
  push:
    paths:
      - 'paper/paper.md'
      - 'paper/paper.bib'

jobs:
  paper:
    runs-on: ubuntu-latest
    name: Paper Draft
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build draft PDF
        uses: openjournals/openjournals-draft-action@master
        with:
          journal: joss
          paper-path: paper/paper.md

      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: paper
          path: paper/paper.pdf

      - name: Commit and Push PDF
        run: |
          git config --local user.email "90641828+GeorgeVassilakis@users.noreply.github.com"
          git config --local user.name "GeorgeVassilakis"
          git add paper/paper.pdf
          git commit -m "Update PDF" || echo "No changes to commit"
          git push